[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "certspy"
version = "0.2.0"

description = "A Python client for the crt.sh website to retrieve subdomains information."
readme = "README.md"
requires-python = ">=3.7"

authors = [{name = "Omar Santos", email = "santosomar@gmail.com"}]
license = "BSD-3-Clause"

dependencies = [
    "requests",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["certspy"]

[project.scripts]
certspy = 'certspy:main'
